"""
Golden reference integration tests for Phase 2 quantization core.

Verifies that new src/ implementations produce bit-identical output
against pre-captured golden reference files (generated by capture_golden.py).
"""
import os
import pytest
import torch

from src.quantize.elemwise import quantize
from src.quantize.mx_quantize import quantize_mx
from src.quantize.bfloat_quantize import quantize_bfloat
from src.tests._compat import scheme_from_mx_specs

GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "golden")


def _load_golden(filename):
    return torch.load(os.path.join(GOLDEN_DIR, filename), weights_only=False)


# ---------------------------------------------------------------------------
# elemwise_quantize golden files
# ---------------------------------------------------------------------------

ELEMWISE_FORMATS = [
    "mxfp8_e5m2", "mxfp8_e4m3", "mxfp6_e3m2", "mxfp6_e2m3",
    "mxfp4_e2m1", "mxint8", "mxint4", "mxint2", "bfloat16",
]


@pytest.mark.parametrize("cfg_name", ELEMWISE_FORMATS)
def test_elemwise_quantize_golden(cfg_name):
    golden = _load_golden(f"elemwise_quantize_{cfg_name}.pt")
    info = scheme_from_mx_specs(golden["mx_specs"])
    assert info is not None, f"Expected non-None scheme for {cfg_name}"
    new_out = quantize(
        golden["input"].clone(),
        info.scheme,
        allow_denorm=info.allow_denorm,
    )
    assert torch.equal(new_out, golden["output"]), \
        f"elemwise golden mismatch for {cfg_name}"


# ---------------------------------------------------------------------------
# quantize_bfloat golden files
# ---------------------------------------------------------------------------

BFLOAT_FORMATS = [
    "bfloat16", "mxfp8_e5m2", "mxfp8_e4m3", "mxfp6_e3m2", "mxfp6_e2m3",
    "mxfp4_e2m1", "mxint8", "mxint4", "mxint2",
]


@pytest.mark.parametrize("cfg_name", BFLOAT_FORMATS)
def test_quantize_bfloat_golden(cfg_name):
    golden = _load_golden(f"quantize_bfloat_{cfg_name}.pt")
    info = scheme_from_mx_specs(golden["mx_specs"])
    assert info is not None, f"Expected non-None scheme for {cfg_name}"
    new_out = quantize_bfloat(
        golden["input"].clone(),
        info.scheme,
        allow_denorm=info.allow_denorm,
    )
    assert torch.equal(new_out, golden["output"]), \
        f"bfloat golden mismatch for {cfg_name}"


# ---------------------------------------------------------------------------
# mx_quantize golden files
# ---------------------------------------------------------------------------

MX_QUANTIZE_FORMATS = [
    "fp8_e5m2", "fp8_e4m3", "fp6_e3m2", "fp6_e2m3",
    "fp4_e2m1", "int8", "int4", "int2",
]


@pytest.mark.parametrize("fmt", MX_QUANTIZE_FORMATS)
def test_mx_quantize_golden(fmt):
    golden = _load_golden(f"mx_quantize_{fmt}_bs32.pt")
    info = scheme_from_mx_specs(golden["mx_specs"], use_mx_format=True)
    assert info is not None, f"Expected non-None scheme for {fmt}"
    new_out = quantize_mx(
        golden["input"].clone(),
        info.scheme,
        axes=[-1],
    )
    assert torch.equal(new_out, golden["output"]), \
        f"mx golden mismatch for {fmt}"
